export const HS_SKILLS = {
  AREAS_Y_ROLES: {
    "Seguridad defensiva": [
      "SOC Analyst L1",
      "SOC Analyst L2",
      "SOC Analyst L3",
      "Security Monitoring Analyst",
      "Detection Engineer",
      "Threat Hunter",
      "Incident Responder",
      "Incident Handler",
      "Digital Forensics Analyst",
      "Malware Analyst",
      "Cyber Threat Intelligence Analyst",
      "Vulnerability Management Analyst",
      "SIEM Engineer",
      "Blue Team Specialist",
      "SOC Team Lead",
      "SOC Manager",
    ],
    "Seguridad ofensiva": [
      "Junior Penetration Tester",
      "Penetration Tester",
      "Web Application Pentester",
      "Infrastructure Pentester",
      "Active Directory Pentester",
      "API Pentester",
      "Mobile Pentester",
      "Cloud Pentester",
      "Red Team Operator",
      "Red Team Lead",
      "Adversary Emulation Specialist",
      "Exploit Developer",
      "Social Engineering Specialist",
      "Bug Bounty Hunter",
    ],
    "Gobierno, riesgo y cumplimiento": [
      "GRC Analyst",
      "IT Risk Analyst",
      "Cyber Risk Analyst",
      "Compliance Analyst",
      "Security Auditor",
      "IT Auditor",
      "Third-Party Risk Analyst",
      "Business Continuity Analyst",
      "Privacy Analyst",
      "Data Protection Analyst",
      "Security Awareness Specialist",
      "GRC Manager",
    ],
    "Identidad y gestión de accesos": [
      "IAM Analyst",
      "IAM Engineer",
      "IAM Architect",
      "PAM Specialist",
      "Identity Governance Analyst",
      "Active Directory Security Specialist",
      "Microsoft Entra ID Security Specialist",
      "IAM Manager",
    ],
    "Seguridad cloud": [
      "Cloud Security Analyst",
      "Cloud Security Engineer",
      "Cloud Security Architect",
      "Cloud Incident Responder",
      "Cloud Detection Engineer",
      "Cloud Security Posture Analyst",
      "AWS Security Specialist",
      "Azure Security Specialist",
      "Google Cloud Security Specialist",
    ],
    "Seguridad de aplicaciones": [
      "Application Security Analyst",
      "Application Security Engineer",
      "Product Security Analyst",
      "Product Security Engineer",
      "Secure Code Reviewer",
      "DevSecOps Engineer",
      "Security Champion",
      "API Security Specialist",
      "Mobile Application Security Analyst",
    ],
    "Arquitectura e ingeniería de seguridad": [
      "Security Engineer",
      "Network Security Engineer",
      "Endpoint Security Engineer",
      "Security Architect",
      "Enterprise Security Architect",
      "Cybersecurity Consultant",
      "Security Solutions Architect",
    ],
    "Seguridad de datos y privacidad": [
      "Data Security Analyst",
      "Data Loss Prevention Analyst",
      "Privacy Analyst",
      "Data Protection Officer",
      "Database Security Specialist",
      "Information Protection Specialist",
    ],
    "Seguridad OT, ICS e IoT": [
      "OT Security Analyst",
      "ICS Security Analyst",
      "OT Incident Responder",
      "Industrial Security Engineer",
      "IoT Security Analyst",
      "OT Security Architect",
    ],
    "Fraude y abuso digital": [
      "Fraud Analyst",
      "Digital Fraud Investigator",
      "Brand Protection Analyst",
      "Anti-Abuse Analyst",
      "Account Takeover Analyst",
      "Digital Risk Protection Analyst",
    ],
    "Liderazgo y gestión": [
      "Cybersecurity Team Lead",
      "SOC Manager",
      "Incident Response Manager",
      "Security Operations Manager",
      "Cybersecurity Manager",
      "Head of Cybersecurity",
      "Security Director",
      "CISO",
      "vCISO",
    ],
  },

  // ── 2. HABILIDADES ────────────────────────────────────────────────────────
  // Estructura: grupo → array de habilidades (nombre canónico de display)
  HABILIDADES: {
    "Fundamentos": [
      "Zero Trust",
      "Gestión de superficie de ataque",
      "Modelado de amenazas",
      "Gestión de controles de seguridad",
      "Identificación de riesgos",
      "Evaluación de riesgos",
      "Análisis de impacto",
      "Tratamiento de riesgos",
      "Riesgo inherente",
      "Riesgo residual",
      "Evaluación de controles",
      "PKI",
      "TLS",
      "Gestión de claves",
      "Gestión de secretos",
      "Fundamentos de ciberseguridad",
      "Criptografía aplicada",
    ],
    "Operaciones SOC": [
      "Monitoreo de alertas",
      "Triage de alertas",
      "Clasificación de incidentes",
      "Priorización de alertas",
      "Evaluación de severidad",
      "Validación de falsos positivos",
      "Correlación de eventos",
      "Enriquecimiento de alertas",
      "Escalamiento de incidentes",
      "Gestión de casos",
      "Documentación de alertas",
      "Seguimiento de tickets",
      "Manejo de SLA",
      "Handover entre turnos",
      "Análisis de logs",
      "Análisis de procesos",
      "Análisis de árbol de procesos",
      "Análisis de línea de comandos",
      "Análisis de autenticaciones",
      "Análisis de tráfico de red",
      "Análisis de DNS",
      "Análisis de proxy",
      "Análisis de correo electrónico",
      "Análisis de phishing",
      "Análisis básico de malware",
      "Análisis de comportamiento",
      "Construcción de líneas de tiempo",
      "Determinación de alcance",
      "Identificación de causa raíz",
      "Identificación de IOC",
      "Análisis de endpoints",
      "Análisis de actividad de usuarios",
    ],
    "Detección": [
      "Creación de reglas de detección",
      "Ajuste de reglas de detección",
      "Reducción de falsos positivos",
      "Cobertura de detección",
      "Validación de reglas",
      "Detection as Code",
      "Mapeo con MITRE ATT&CK",
      "Priorización de casos de uso",
      "Desarrollo de casos de uso",
      "Testing de detecciones",
      "Simulación de ataques",
      "Purple Teaming",
      "Gestión del ciclo de vida de detecciones",
      "Análisis de brechas de cobertura",
      "Detección basada en IOC",
      "Detección basada en comportamiento",
      "Detección basada en anomalías",
      "Detección basada en TTP",
      "Detección de persistencia",
      "Detección de ejecución",
      "Detección de movimiento lateral",
      "Detección de exfiltración",
      "Detección de abuso de credenciales",
      "Detección de LOLBins",
      "Detección de living-off-the-land",
      "Detección de herramientas remotas",
    ],
    "Threat Hunting": [
      "Desarrollo de hipótesis",
      "Hunting basado en inteligencia",
      "Hunting basado en TTP",
      "Hunting basado en anomalías",
      "Hunting basado en comportamiento",
      "Hunting basado en IOC",
      "Scoping de investigación",
      "Baseline de comportamiento",
      "Identificación de desviaciones",
      "Validación de hipótesis",
      "Documentación de hunting",
      "Conversión de hallazgos en detecciones",
      "Identificación de brechas de visibilidad",
      "Priorización de hunts",
      "Análisis de telemetría EDR",
      "Análisis de persistencia",
      "Análisis de movimiento lateral",
      "Análisis de credenciales",
      "Análisis de ejecución remota",
      "Análisis de PowerShell",
      "Análisis de LOLBins",
      "Análisis de actividad cloud",
      "Análisis temporal",
      "Análisis de cadenas de ejecución",
      "Análisis de comportamiento de cuentas de servicio",
      "Análisis de exfiltración",
      "Análisis de beaconing",
    ],
    "Incident Response": [
      "Preparación para incidentes",
      "Desarrollo de playbooks",
      "Desarrollo de planes de respuesta",
      "Tabletop exercises",
      "Definición de roles de respuesta",
      "Matriz de escalamiento",
      "Identificación de incidentes",
      "Contención",
      "Erradicación",
      "Recuperación",
      "Lecciones aprendidas",
      "Coordinación de incidentes",
      "Gestión de crisis",
      "Comunicación de incidentes",
      "Preservación de evidencias",
      "Determinación de impacto",
      "Análisis de causa raíz",
      "Post-incident review",
      "Respuesta a ransomware",
      "Respuesta a phishing",
      "Respuesta a malware",
      "Respuesta a compromiso de cuentas",
      "Respuesta a fuga de información",
      "Respuesta a ataques web",
      "Respuesta a compromiso cloud",
      "Respuesta a abuso de privilegios",
      "Respuesta a insider threat",
      "Respuesta a fraude digital",
      "Respuesta a compromiso de Active Directory",
    ],
    "Threat Intelligence": [
      "Dirección de inteligencia",
      "Recolección de inteligencia",
      "Procesamiento de inteligencia",
      "Análisis de inteligencia",
      "Producción de inteligencia",
      "Diseminación de inteligencia",
      "Retroalimentación de inteligencia",
      "Inteligencia estratégica",
      "Inteligencia operacional",
      "Inteligencia táctica",
      "Inteligencia técnica",
      "Análisis de actores de amenaza",
      "Análisis de campañas",
      "Análisis de infraestructura maliciosa",
      "Investigación de dominios",
      "Investigación de direcciones IP",
      "Análisis de certificados",
      "Análisis de WHOIS",
      "Análisis de ASN",
      "Enriquecimiento de IOC",
      "Evaluación de confiabilidad",
      "Evaluación de relevancia",
      "Priorización de inteligencia",
      "Perfilado de adversarios",
      "Dark web monitoring",
      "Brand monitoring",
      "Digital risk protection",
    ],
    "Malware": [
      "Análisis estático de malware",
      "Análisis dinámico de malware",
      "Análisis de headers PE",
      "Análisis de archivos ELF",
      "Análisis de importaciones y exportaciones",
      "Análisis de secciones PE",
      "Identificación de packers",
      "Identificación de ofuscación",
      "Reverse engineering",
      "Análisis en sandbox",
      "Debugging",
      "Monitoreo de procesos",
      "Monitoreo de archivos",
      "Monitoreo del registro",
      "Monitoreo de red",
      "Extracción de configuración",
      "Extracción de IOC",
      "Desempaquetado de malware",
    ],
    "Forense digital": [
      "Adquisición forense",
      "Preservación de evidencia",
      "Cadena de custodia",
      "Análisis de disco",
      "Análisis de memoria",
      "Análisis del registro de Windows",
      "Análisis de Prefetch",
      "Análisis de Amcache",
      "Análisis de Shimcache",
      "Análisis de eventos de Windows",
      "Análisis de MFT",
      "Análisis de USN Journal",
      "Análisis de artefactos de navegador",
      "Recuperación de archivos",
      "Análisis de PCAP",
      "Reconstrucción de sesiones",
      "Análisis HTTP",
      "Análisis TLS",
      "Análisis NetFlow",
      "Forense cloud",
      "Forense de dispositivos móviles",
    ],
    "Seguridad ofensiva": [
      "Reconocimiento pasivo",
      "Reconocimiento activo",
      "Enumeración",
      "Scanning",
      "Explotación",
      "Post-explotación",
      "Escalamiento de privilegios",
      "Movimiento lateral",
      "Persistencia ofensiva",
      "Exfiltración simulada",
      "Elaboración de reportes de pentesting",
      "Retesting",
      "Gestión de evidencias de pentesting",
      "SQL Injection",
      "Cross-Site Scripting",
      "CSRF",
      "SSRF",
      "XXE",
      "IDOR",
      "Path Traversal",
      "Command Injection",
      "File Inclusion",
      "Authentication Bypass",
      "Session Management Testing",
      "Business Logic Testing",
      "API Security Testing",
      "GraphQL Security Testing",
      "File Upload Testing",
      "Deserialization Testing",
      "JWT Security Testing",
      "Network Pentesting",
      "Active Directory Pentesting",
      "SMB Enumeration",
      "LDAP Enumeration",
      "Kerberos Attacks",
      "NTLM Attacks",
      "Password Spraying",
      "Credential Dumping",
      "Pivoting",
      "Tunneling",
      "Wireless Pentesting",
      "AD CS Abuse",
      "Kerberoasting",
      "AS-REP Roasting",
    ],
    "Vulnerabilidades": [
      "Descubrimiento de activos",
      "Scanning de vulnerabilidades",
      "Validación de vulnerabilidades",
      "Priorización de vulnerabilidades",
      "Análisis de exploitabilidad",
      "Gestión de remediación",
      "Seguimiento de parches",
      "Gestión de excepciones",
      "Gestión de falsos positivos",
      "Vulnerability intelligence",
      "Attack Surface Management",
      "External Attack Surface Management",
      "Gestión de exposición",
      "Análisis CVSS",
      "Análisis EPSS",
      "Priorización basada en KEV",
    ],
    "AppSec": [
      "Secure SDLC",
      "Threat Modeling",
      "Secure Coding",
      "Secure Code Review",
      "Security Requirements",
      "Security Architecture Review",
      "Dependency Management",
      "SAST",
      "DAST",
      "IAST",
      "RASP",
      "SCA",
      "Container Scanning",
      "Fuzzing",
      "Mobile Application Security Testing",
      "Secrets Scanning",
      "Supply Chain Security",
      "SBOM",
    ],
    "Cloud Security": [
      "Cloud IAM",
      "Cloud Logging",
      "Cloud Monitoring",
      "Cloud Network Security",
      "Cloud Incident Response",
      "Cloud Threat Detection",
      "Cloud Security Posture Management",
      "Cloud Workload Protection",
      "Cloud Infrastructure Entitlement Management",
      "Cloud Data Security",
      "Cloud Key Management",
      "Cloud Secrets Management",
      "Cloud Architecture Review",
      "Multi-cloud Security",
      "Cloud Compliance",
    ],
    "IAM y PAM": [
      "Gestión de identidades",
      "Provisioning",
      "Deprovisioning",
      "Single Sign-On",
      "Multi-Factor Authentication",
      "Federation",
      "Identity Lifecycle Management",
      "Role-Based Access Control",
      "Attribute-Based Access Control",
      "Access Reviews",
      "Identity Governance",
      "Privileged Access Management",
      "Privileged Identity Management",
      "Segregation of Duties",
      "JIT Access",
      "Passwordless Authentication",
    ],
    "Redes": [
      "Modelo OSI",
      "TCP/IP",
      "Subnetting",
      "Routing",
      "Switching",
      "VLAN",
      "NAT",
      "VPN",
      "Proxy",
      "Load Balancing",
      "Network Segmentation",
      "Microsegmentation",
      "Network Traffic Analysis",
      "Packet Analysis",
      "Firewall Management",
      "IDS",
      "IPS",
      "Network Access Control",
      "Web Application Firewall",
      "Secure Web Gateway",
      "DNS Security",
      "Email Security",
      "DDoS Protection",
    ],
    "Programación y automatización": [
      "Scripting",
      "Automatización de tareas",
      "Automatización de respuesta",
      "Desarrollo de integraciones",
      "Integración de APIs",
      "REST APIs",
      "Webhooks",
      "Parsing de JSON",
      "Parsing de XML",
      "Expresiones regulares",
      "Desarrollo de playbooks",
      "Orquestación",
      "Infraestructura como código",
      "Versionado con Git",
      "Desarrollo de scripts de seguridad",
    ],
    "DevSecOps": [
      "CI/CD Security",
      "Pipeline Security",
      "Container Security",
      "Kubernetes Security",
      "Image Scanning",
      "Runtime Security",
      "Admission Control",
      "Infrastructure as Code Security",
      "Policy as Code",
      "Artifact Signing",
      "Dependency Scanning",
      "Secrets Management en CI/CD",
      "Supply Chain Security",
    ],
    "GRC": [
      "Gobierno de seguridad",
      "Desarrollo de políticas",
      "Desarrollo de estándares",
      "Desarrollo de procedimientos",
      "Gestión de controles",
      "Security Awareness",
      "Gestión de terceros",
      "Third-Party Risk Management",
      "Auditoría de seguridad",
      "Auditoría de sistemas",
      "Gestión de cumplimiento",
      "Business Continuity",
      "Disaster Recovery",
      "Business Impact Analysis",
      "Crisis Management",
      "Disaster Recovery Testing",
      "Evaluación de impacto de privacidad",
      "Gestión de consentimiento",
      "Gestión de riesgos de ciberseguridad",
    ],
    "IA aplicada": [
      "IA para análisis de alertas",
      "IA para investigación de incidentes",
      "IA para threat hunting",
      "IA para enriquecimiento de IOC",
      "Generación asistida de queries",
      "Automatización asistida por IA",
      "Validación de respuestas generadas por IA",
      "Prompt Engineering para ciberseguridad",
      "Evaluación de alucinaciones",
      "Uso seguro de asistentes de IA",
      "AI Security",
      "LLM Security",
      "Prompt Injection",
      "Model Abuse",
      "Data Poisoning",
      "Model Extraction",
      "Insecure Output Handling",
      "AI Governance",
    ],
    "Habilidades analíticas": [
      "Pensamiento analítico",
      "Pensamiento crítico",
      "Reconocimiento de patrones",
      "Formulación de hipótesis",
      "Resolución de problemas",
      "Toma de decisiones",
      "Priorización",
      "Análisis de causa raíz",
      "Manejo de incertidumbre",
      "Evaluación de evidencia",
      "Correlación de información",
      "Atención al detalle",
      "Orientación a riesgos",
      "Capacidad investigativa",
      "Curiosidad técnica",
    ],
    "Habilidades profesionales": [
      "Comunicación escrita",
      "Comunicación oral",
      "Redacción técnica",
      "Redacción ejecutiva",
      "Presentación de hallazgos",
      "Comunicación con clientes",
      "Comunicación con equipos técnicos",
      "Comunicación con liderazgo",
      "Traducción de riesgos técnicos",
      "Storytelling de seguridad",
      "Trabajo en equipo",
      "Colaboración interdisciplinaria",
      "Escucha activa",
      "Gestión de conflictos",
      "Mentoring",
      "Liderazgo",
      "Delegación",
      "Coordinación de equipos",
      "Gestión del tiempo",
      "Organización",
      "Autonomía",
      "Adaptabilidad",
      "Aprendizaje continuo",
      "Responsabilidad",
      "Proactividad",
      "Orientación a resultados",
      "Manejo de prioridades",
      "Trabajo bajo presión",
      "Ética profesional",
      "Comunicación en crisis",
      "Manejo de stakeholders",
    ],
    "Tecnologías": [
      "Windows",
      "Windows Server",
      "Linux",
      "Ubuntu",
      "Debian",
      "Red Hat Enterprise Linux",
      "CentOS",
      "Rocky Linux",
      "Kali Linux",
      "macOS",
      "Android",
      "iOS",
      "Unix",
      "ChromeOS",
      "Active Directory",
      "Microsoft Entra ID",
      "LDAP",
      "Kerberos",
      "Group Policy",
      "Microsoft 365",
      "Google Workspace",
      "Amazon Web Services",
      "Microsoft Azure",
      "Google Cloud Platform",
      "Oracle Cloud Infrastructure",
      "IBM Cloud",
      "Docker",
      "Kubernetes",
      "OpenShift",
      "VMware",
      "Hyper-V",
      "VirtualBox",
      "Podman",
      "TCP",
      "UDP",
      "ICMP",
      "ARP",
      "DNS",
      "DHCP",
      "HTTP",
      "HTTPS",
      "FTP",
      "SFTP",
      "SSH",
      "SMTP",
      "IMAP",
      "POP3",
      "SMB",
      "RDP",
      "SNMP",
      "NTP",
      "BGP",
      "Firewall",
    ],
    "Lenguajes de programación y scripting": [
      "Python",
      "PowerShell",
      "Bash",
      "JavaScript",
      "TypeScript",
      "Java",
      "C",
      "C++",
      "C#",
      "Go",
      "Rust",
      "PHP",
      "Ruby",
      "SQL",
      "Assembly",
      "Visual Basic",
      "Perl",
    ],
    "Lenguajes de consulta y reglas": [
      "KQL",
      "SPL",
      "AQL",
      "LogScale Query Language",
      "Lucene Query Syntax",
      "Elastic Query DSL",
      "EQL",
      "XQL",
      "YARA",
      "YARA-L",
      "Sigma",
      "Snort Rules",
      "Suricata Rules",
      "Regular Expressions",
      "GraphQL",
    ],
    "Marcos y metodologías": [
      "MITRE ATT&CK",
      "Cyber Kill Chain",
      "Diamond Model",
      "Pyramid of Pain",
      "NIST Cybersecurity Framework",
      "NIST Incident Response",
      "NIST SP 800-53",
      "ISO 27001",
      "ISO 27002",
      "CIS Controls",
      "OWASP Top 10",
      "OWASP ASVS",
      "OWASP SAMM",
      "OWASP Web Security Testing Guide",
      "PCI DSS",
      "SOC 2",
      "COBIT",
      "ITIL",
      "STRIDE",
      "PASTA",
      "DREAD",
      "CVSS",
      "CVE",
      "CWE",
      "CAPEC",
      "EPSS",
      "CISA KEV",
      "TLP",
      "STIX",
      "TAXII",
      "SANS Incident Response Process",
      "PTES",
      "OSSTMM",
    ],
  },

  HERRAMIENTAS: {
    "SIEM": [
      "Microsoft Sentinel",
      "Splunk Enterprise",
      "Splunk Enterprise Security",
      "IBM QRadar",
      "Elastic Security",
      "Google Security Operations",
      "LogRhythm SIEM",
      "OpenText ArcSight",
      "Exabeam",
      "Rapid7 InsightIDR",
      "Sumo Logic",
      "Devo",
      "Wazuh",
      "Graylog",
      "Fortinet FortiSIEM",
      "ManageEngine Log360",
    ],
    "EDR / XDR": [
      "CrowdStrike Falcon",
      "Microsoft Defender for Endpoint",
      "Microsoft Defender XDR",
      "SentinelOne Singularity",
      "Palo Alto Cortex XDR",
      "Trend Micro Vision One",
      "VMware Carbon Black",
      "Sophos Intercept X",
      "Trellix Endpoint Security",
      "Elastic Defend",
      "Cisco Secure Endpoint",
      "Cybereason",
      "Fortinet FortiEDR",
      "Bitdefender GravityZone",
    ],
    "SOAR y gestión de casos": [
      "Palo Alto Cortex XSOAR",
      "Splunk SOAR",
      "Microsoft Sentinel Playbooks",
      "IBM Security SOAR",
      "Tines",
      "Swimlane",
      "Torq",
      "FortiSOAR",
      "Rapid7 InsightConnect",
      "Google Security Operations SOAR",
      "Shuffle",
      "TheHive",
      "Cortex",
      "ServiceNow",
      "Jira Service Management",
    ],
    "Threat Intelligence / OSINT": [
      "MISP",
      "OpenCTI",
      "VirusTotal",
      "Recorded Future",
      "Intel 471",
      "CrowdStrike Falcon Intelligence",
      "ThreatConnect",
      "Anomali ThreatStream",
      "AlienVault OTX",
      "Maltego",
      "Shodan",
      "Censys",
      "GreyNoise",
      "DomainTools",
      "Microsoft Defender Threat Intelligence",
      "Feedly",
    ],
    "Gestión de vulnerabilidades": [
      "Tenable Nessus",
      "Tenable Vulnerability Management",
      "Qualys VMDR",
      "Rapid7 InsightVM",
      "Greenbone",
      "OpenVAS",
      "Microsoft Defender Vulnerability Management",
      "CrowdStrike Falcon Exposure Management",
      "Tenable Security Center",
      "Nuclei",
      "Nexpose",
      "Acunetix",
      "Invicti",
      "Burp Suite Enterprise Edition",
    ],
    "Pentesting web / API": [
      "Burp Suite",
      "OWASP ZAP",
      "sqlmap",
      "Nikto",
      "Nuclei",
      "ffuf",
      "Gobuster",
      "Dirsearch",
      "Postman",
      "Insomnia",
      "Caido",
      "Wfuzz",
      "Commix",
      "Dalfox",
      "Amass",
      "Subfinder",
      "httpx",
    ],
    "Pentesting de infraestructura / AD": [
      "Nmap",
      "Masscan",
      "Metasploit Framework",
      "NetExec",
      "CrackMapExec",
      "Impacket",
      "Responder",
      "Mimikatz",
      "BloodHound",
      "SharpHound",
      "PowerView",
      "Rubeus",
      "Certipy",
      "Evil-WinRM",
      "Hydra",
      "John the Ripper",
      "Hashcat",
      "Kerbrute",
      "enum4linux",
      "smbclient",
      "Chisel",
      "Ligolo-ng",
      "ProxyChains",
    ],
    "Forense digital": [
      "Autopsy",
      "The Sleuth Kit",
      "EnCase",
      "FTK",
      "FTK Imager",
      "Magnet AXIOM",
      "KAPE",
      "Velociraptor",
      "Volatility",
      "Volatility 3",
      "Eric Zimmerman Tools",
      "Plaso",
      "Log2Timeline",
      "Wireshark",
      "NetworkMiner",
      "X-Ways Forensics",
      "SIFT Workstation",
      "ALEAPP",
      "iLEAPP",
    ],
    "Malware analysis / reversing": [
      "Ghidra",
      "IDA Pro",
      "IDA Free",
      "x64dbg",
      "WinDbg",
      "OllyDbg",
      "Radare2",
      "Cutter",
      "Binary Ninja",
      "Detect It Easy",
      "PEStudio",
      "PE-bear",
      "Process Monitor",
      "Process Explorer",
      "Autoruns",
      "API Monitor",
      "Regshot",
      "FakeNet-NG",
      "INetSim",
      "Cuckoo Sandbox",
      "CAPEv2",
      "Joe Sandbox",
      "ANY.RUN",
      "REMnux",
      "FLARE-VM",
      "YARA",
      "CyberChef",
    ],
    "Cloud Security": [
      "AWS GuardDuty",
      "AWS Security Hub",
      "AWS Inspector",
      "AWS Config",
      "AWS CloudTrail",
      "AWS IAM Access Analyzer",
      "Microsoft Defender for Cloud",
      "Azure Monitor",
      "Azure Policy",
      "Azure Key Vault",
      "Google Security Command Center",
      "Google Cloud Logging",
      "Google Cloud Audit Logs",
      "Wiz",
      "Prisma Cloud",
      "Orca Security",
      "Lacework",
      "Check Point CloudGuard",
      "Tenable Cloud Security",
      "CrowdStrike Falcon Cloud Security",
      "Sysdig Secure",
      "Aqua Security",
      "Prowler",
      "ScoutSuite",
      "CloudSploit",
      "Steampipe",
    ],
    "IAM / PAM": [
      "Microsoft Active Directory",
      "Microsoft Entra ID",
      "Okta",
      "CyberArk",
      "SailPoint",
      "BeyondTrust",
      "Ping Identity",
      "One Identity",
      "Saviynt",
      "ForgeRock",
      "Delinea",
      "Microsoft Entra Privileged Identity Management",
      "AWS IAM",
      "Google Cloud IAM",
      "HashiCorp Vault",
      "Keycloak",
      "JumpCloud",
    ],
    "Network Security": [
      "Palo Alto Networks NGFW",
      "Fortinet FortiGate",
      "Check Point Firewall",
      "Cisco Firepower",
      "Cisco ASA",
      "Juniper SRX",
      "Sophos Firewall",
      "Cloudflare",
      "Zscaler",
      "Netskope",
      "F5 BIG-IP",
      "Imperva Web Application Firewall",
      "AWS WAF",
      "Azure Web Application Firewall",
      "Snort",
      "Suricata",
      "Zeek",
      "Cisco Secure Network Analytics",
      "Darktrace",
      "ExtraHop RevealX",
      "Corelight",
      "tcpdump",
      "TShark",
    ],
    "AppSec / DevSecOps": [
      "SonarQube",
      "Checkmarx",
      "Veracode",
      "Snyk",
      "GitHub Advanced Security",
      "GitLab Security",
      "Semgrep",
      "Fortify",
      "Black Duck",
      "Mend",
      "Trivy",
      "Grype",
      "Clair",
      "Anchore",
      "OWASP Dependency-Check",
      "Gitleaks",
      "TruffleHog",
      "Checkov",
      "Terrascan",
      "KICS",
      "Falco",
      "Cosign",
      "Syft",
      "Dependency-Track",
    ],
    "Email Security / Awareness": [
      "Microsoft Defender for Office 365",
      "Proofpoint",
      "Mimecast",
      "Cisco Secure Email",
      "Abnormal Security",
      "Barracuda Email Protection",
      "FortiMail",
      "Google Workspace Security",
      "KnowBe4",
      "Cofense",
      "Proofpoint Security Awareness",
    ],
    "DLP / Data Security": [
      "Microsoft Purview",
      "Symantec Data Loss Prevention",
      "Forcepoint DLP",
      "Trellix Data Loss Prevention",
      "Netskope DLP",
      "Digital Guardian",
      "CoSoSys Endpoint Protector",
      "Varonis",
      "BigID",
      "Imperva Data Security",
    ],
  },

} as const;

// ── Helpers de acceso rápido ──────────────────────────────────────────────────

/** Todos los roles de todas las áreas como array plano */
export const ALL_ROLES: string[] = Object.values(HS_SKILLS.AREAS_Y_ROLES).flat();

/** Todas las habilidades de todos los grupos como array plano */
export const ALL_HABILIDADES: string[] = Object.values(HS_SKILLS.HABILIDADES).flat();

/** Todas las herramientas de todas las categorías como array plano */
export const ALL_HERRAMIENTAS: string[] = Object.values(HS_SKILLS.HERRAMIENTAS).flat();

/** Todo el catálogo unificado como array plano (para búsqueda general) */
export const ALL_SKILLS_FLAT: string[] = [ ...ALL_ROLES, ...ALL_HABILIDADES, ...ALL_HERRAMIENTAS, ];

export default HS_SKILLS;